name: ansar_rental
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-255.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.20.0
  firebase_auth: 3.6.0
  cloud_firestore: 3.4.1
  freezed_annotation: 2.1.0
  json_annotation: 4.6.0
  velocity_x: 3.5.1
  flutter_screenutil: 5.5.3+2
  google_fonts: 3.0.1
  get_storage: 2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.2.0
  flutter_lints: 2.0.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

