name: ansar_rental
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-255.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.20.0
  firebase_auth: 3.6.0
  cloud_firestore: 3.4.1
  freezed_annotation: 2.1.0
  json_annotation: 4.6.0
  velocity_x: 3.5.1
  flutter_screenutil: 5.5.3+2
  google_fonts: 3.0.1
  get_storage: 2.0.3
  iconsax: 0.0.8
  dartz: 0.10.1
  lottie: 1.4.0
  image_picker: 0.8.5+3
  image_cropper: 2.0.3
  cached_network_image: 3.2.1
  firebase_storage: 10.3.4
  open_file_safe: 3.2.3
  url_launcher: 6.1.5
  flutter_cache_manager: 3.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.2.0
  flutter_lints: 2.0.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/
  uses-material-design: true

