// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK_bWmHlLlYBJdb7jhqpj7JWAvt76UcYU',
    appId: '1:641632887618:web:b3676bb2437c5546b75edb',
    messagingSenderId: '641632887618',
    projectId: 'ansarrental-5d261',
    authDomain: 'ansarrental-5d261.firebaseapp.com',
    storageBucket: 'ansarrental-5d261.appspot.com',
    measurementId: 'G-EG2S62DGTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACY_Rc5GKnflJI65QNwcQC0uSZsdTlYJo',
    appId: '1:641632887618:android:d2779b0bc0330911b75edb',
    messagingSenderId: '641632887618',
    projectId: 'ansarrental-5d261',
    storageBucket: 'ansarrental-5d261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9WhwNMVonRV3SX4TNTLbjD9-EkKlJyzw',
    appId: '1:641632887618:ios:cf65c0f72e4425fbb75edb',
    messagingSenderId: '641632887618',
    projectId: 'ansarrental-5d261',
    storageBucket: 'ansarrental-5d261.appspot.com',
    iosClientId:
        '641632887618-hhn0tn43d7kon1p9pv5qfa17f6vk63mv.apps.googleusercontent.com',
    iosBundleId: 'com.abhi.ansarirental.ansarRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9WhwNMVonRV3SX4TNTLbjD9-EkKlJyzw',
    appId: '1:641632887618:ios:cf65c0f72e4425fbb75edb',
    messagingSenderId: '641632887618',
    projectId: 'ansarrental-5d261',
    storageBucket: 'ansarrental-5d261.appspot.com',
    iosClientId:
        '641632887618-hhn0tn43d7kon1p9pv5qfa17f6vk63mv.apps.googleusercontent.com',
    iosBundleId: 'com.abhi.ansarirental.ansarRental',
  );
}
